/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_toshiba_ffmpeg_FFmpegCmd */

#ifndef _Included_com_toshiba_ffmpeg_FFmpegCmd
#define _Included_com_toshiba_ffmpeg_FFmpegCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_toshiba_ffmpeg_FFmpegCmd
 * Method:    exec
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_toshiba_ffmpeg_FFmpegCmd_exec
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
