/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ffmpeg_spc_myapplication_FFmpegCmd */

#ifndef _Included_ffmpeg_spc_myapplication_FFmpegCmd
#define _Included_ffmpeg_spc_myapplication_FFmpegCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffmpeg_spc_myapplication_FFmpegCmd
 * Method:    exec
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ffmpeg_spc_myapplication_FFmpegCmd_exec
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
